name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore
    - name: Publish Live
      run: dotnet nuget push **/*.nupkg -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json -n true
      env:
         NUGET_TOKEN: ${{secrets.PUBLIC_NUGET_TOKEN}}

    - name: Publish Proget
      run: dotnet nuget push **/*.nupkg -k ${NUGET_KEY} -s ${NUGET_SOURCE} -n true
      env:
         NUGET_SOURCE: ${{secrets.PROGET_NUGET}}
         NUGET_KEY: ${{secrets.PROGET_NUGET_TOKEN}}  


    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          const { NBGV_SemVer2 } = process.env
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: `refs/tags/v${NBGV_SemVer2}`,
            sha: context.sha
          })    
